const nodemailer = require('nodemailer');

const sendSupportEmail = async (req, res) => {
    try {
        const { name, email, message } = req.body;

        if (!name || !email || !message) {
            return res.status(400).json({ success: false, message: 'Please fill all fields' });
        }

        // 1. Email bhejne wala 'Transporter' setup karo
        const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: process.env.EMAIL_USER, // Tumhara Gmail
                pass: process.env.EMAIL_PASS  // Tumhara Gmail ka 'App Password'
            }
        });

        // 2. Email ka format design karo
        const mailOptions = {
            from: process.env.EMAIL_USER,
            to: process.env.EMAIL_USER, // Yeh email tumhare (Admin) paas aayegi
            replyTo: email, // Jab tum apne Gmail se 'Reply' dabaoge, toh seedha us user ko reply jayega
            subject: `🚨 New Support Ticket from ${name} | EntreSkill`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 10px;">
                    <h2 style="color: #6d28d9; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">New Support Request</h2>
                    <p style="font-size: 16px;"><strong>User Name:</strong> ${name}</p>
                    <p style="font-size: 16px;"><strong>User Email:</strong> ${email}</p>
                    <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin-top: 20px;">
                        <p style="font-size: 14px; color: #64748b; margin-top: 0;">Message / Issue:</p>
                        <p style="font-size: 16px; color: #0f172a; white-space: pre-wrap;">${message}</p>
                    </div>
                    <p style="font-size: 12px; color: #94a3b8; margin-top: 30px; text-align: center;">Generated by EntreSkill System</p>
                </div>
            `
        };

        // 3. Email send karo
        await transporter.sendMail(mailOptions);
        
        res.status(200).json({ success: true, message: 'Support ticket sent successfully!' });

    } catch (error) {
        console.error('Email Sending Error:', error);
        res.status(500).json({ success: false, message: 'Server failed to send email.' });
    }
};

module.exports = { sendSupportEmail };